### ISSUE TITLE
Script died after server downed

### ISSUE THREAD

**Issue by Arayalaa** [sobfiggis/Avabur_Enhancer#12]
Probably core code rewrite that made the script nonfunctional.

**Comment by sobfiggis** [comment]
So far script appears to be running fine, though a bunch of Vsyn's code is having issues at the moment. What errors are you receiving in the console?

**Comment by Arayalaa** [comment]
game.php:1 The SSL certificate used to load resources from https://steamuserimages-a.akamaihd.net will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
jquery-1.11.2.min.js:3 GET https://www.avabur.com/css/images/ui-icons_222222_256x240.png 404 ()
Jb @ jquery-1.11.2.min.js:3
css @ jquery-1.11.2.min.js:3
U @ jquery-1.11.2.min.js:3
Vb @ jquery-1.11.2.min.js:3
show @ jquery-1.11.2.min.js:3
m.fn.(anonymous function) @ jquery-1.11.2.min.js:4
$.fn.extend.show @ jquery-ui.js:678
_renderAxis @ jquery-ui.js:460
_create @ jquery-ui.js:462
(anonymous) @ jquery-ui.js:22
_createWidget @ jquery-ui.js:29
$.(anonymous function).(anonymous function) @ jquery-ui.js:21
(anonymous) @ jquery-ui.js:27
each @ jquery-1.11.2.min.js:2
each @ jquery-1.11.2.min.js:2
$.fn.(anonymous function) @ jquery-ui.js:27
(anonymous) @ js.js?t=1514120488:7
j @ jquery-1.11.2.min.js:2
fireWith @ jquery-1.11.2.min.js:2
ready @ jquery-1.11.2.min.js:2
J @ jquery-1.11.2.min.js:2

**Comment by Arayalaa** [comment]
Not sure if this is related, but both enhancer and notifications of avabur died for me at the same time

**Comment by sobfiggis** [comment]
Cyinthia, thank you for the report but this issue is unrelated to this script. Something else you have running is grabbing a picture from Steam's CDN which Google is warning is going to be distrusted.

Some more info if you are curious:
https://www.computerworld.com/article/3184573/security/to-punish-symantec-google-may-distrust-a-third-of-the-webs-ssl-certificates.html
https://forums.aws.amazon.com/thread.jspa?threadID=266912

**Comment by sobfiggis** [comment]
Since the console can be pretty verbose with unrelated errors I'm leaving this issue open in case you have some more information to provide.

**Comment by Arayalaa** [comment]
[Violation] Forced reflow while executing JavaScript took 46ms

Followed by a spammage of 

[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

then

[Violation] 'DOMContentLoaded' handler took 913ms
game.php:1 [DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) <input id=​"current_password_ef" name=​"current_email_ef" type=​"password">​
game.php:1 [DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) <input id=​"current_password" name=​"current_password" type=​"password">​
game.php:1 [DOM] Input elements should have autocomplete attributes (suggested: "new-password"): (More info: https://goo.gl/9p2vKq) <input id=​"new_password" name=​"new_password" type=​"password">​
game.php:1 [DOM] Input elements should have autocomplete attributes (suggested: "new-password"): (More info: https://goo.gl/9p2vKq) <input id=​"new_password_confirm" name=​"new_password_confirm" type=​"password">​
[Violation] Forced reflow while executing JavaScript took 50ms
jquery-1.11.2.min.js:3 GET https://www.avabur.com/css/images/ui-icons_222222_256x240.png 404 ()
Jb @ jquery-1.11.2.min.js:3
css @ jquery-1.11.2.min.js:3
U @ jquery-1.11.2.min.js:3
Vb @ jquery-1.11.2.min.js:3
show @ jquery-1.11.2.min.js:3
m.fn.(anonymous function) @ jquery-1.11.2.min.js:4
$.fn.extend.show @ jquery-ui.js:678
_renderAxis @ jquery-ui.js:460
_create @ jquery-ui.js:462
(anonymous) @ jquery-ui.js:22
_createWidget @ jquery-ui.js:29
$.(anonymous function).(anonymous function) @ jquery-ui.js:21
(anonymous) @ jquery-ui.js:27
each @ jquery-1.11.2.min.js:2
each @ jquery-1.11.2.min.js:2
$.fn.(anonymous function) @ jquery-ui.js:27
(anonymous) @ js.js?t=1514120488:7
j @ jquery-1.11.2.min.js:2
fireWith @ jquery-1.11.2.min.js:2
ready @ jquery-1.11.2.min.js:2
J @ jquery-1.11.2.min.js:2

Then followed by a spammage of till the end of the console

jquery-1.11.2.min.js:3 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

The SSL image thing I believe is the "relics of avabur revamped" background URL link I don't believe it has anything to do with the problem

**Comment by Arayalaa** [comment]
Fixed with a restart 😅
