### ISSUE TITLE
Clan donation table doesn't work after the rewrite

### ISSUE THREAD

**Issue by davidmcclelland** [sobfiggis/Avabur_Enhancer#14]
Someone reported to me that the clan donation table isn't working after changes in the rewrite.

**Comment by sobfiggis** [comment]
Note for myself, update https://github.com/sobfiggis/Avabur_Enhancer/blob/a766b95e198f890cb7370b18de72273de5b38c0e/Avabur_Enhancer.user.js#L284

**Comment by sobfiggis** [comment]
Resolved in 6e1ceb13681c1ceef81e3fb7e27802021ebf837d
