### ISSUE TITLE
Drop tracking for professions doesn't work

### ISSUE THREAD

**Issue by davidmcclelland** [sobfiggis/Avabur_Enhancer#15]
Someone reported to me that drop tracking for crafting/carving is broken after the rewrite changes.

**Comment by edvordo** [comment]
This seems to not be true. When I tested the carving changes, everything on the Drop Tracker window seems to have been updating

![image](https://user-images.githubusercontent.com/6738779/39839246-d7144380-53db-11e8-8526-e1d689ea59f6.png)

**Comment by davidmcclelland** [comment]
Agreed!
